### ISSUE TITLE
请问如何运行

### ISSUE THREAD

**Issue by yueming007** [wed0n/Paster#1]
您好，我是一个小白，请问我下载压缩包解压后，怎么运行程序呀

**Comment by wed0n** [comment]
在 Release 里下载 `Paster.exe`就行了，实在不会就点击下面的链接下载。
https://github.com/wed0n/Paster/releases/download/v0.1.4/Paster.exe

**Comment by wed0n** [comment]
在 Release 里下载 Paster.exe就行了，实在不会就点击下面的链接下载。
https://github.com/wed0n/Paster/releases/download/v0.1.4/Paster.exe
